### ISSUE TITLE
Several bugs in demo inference

### ISSUE THREAD

**Issue by suikei-wang** [kevin-ssy/CLIP_as_RNN#11]
Hi there,

Thanks for the amaing work!

I am trying to set the demo locally however I encoutered various errors.

Firstly, the the `load_sam` function actually pass a Config object instead of a path, so I have to modify it to the following:
```
def load_sam(config, sam_device):
    # Pass the sam checkpoint path from your config
    sam_checkpoint = config.sam.sam_checkpoint  # Assuming this is the path in your config
    model_type = config.sam.model_type     # Assuming this is defined in your config
    
    pipelines = SAMPipeline(
        sam_checkpoint,
        model_type,
        device=sam_device,
        points_per_side=config.sam.points_per_side,
        pred_iou_thresh=config.sam.pred_iou_thresh,
        stability_score_thresh=config.sam.stability_score_thresh,
        box_nms_thresh=config.sam.box_nms_thresh,
    )
    return pipelines
```

Secondly, line 220, ` pseudo_masks, scores, _ = car_model(img, label_space)` has an error that `car_model()` only returns 2 variables. I removed the `_` to "fix" this but I may be wrong.

After all these set, I got the error `RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)`. I was running on GPU and exported GPU path. I have to fix the function as following:
```
def get_sam_masks(config, image_path, masks, img_sam=None, pipeline=None):
    """Get SAM masks online."""
    print("generating sam masks online")
    
    # Get the device that masks is on
    device = masks.device
    
    mask_tensor, mask_list = generate_masks_from_sam(
        image_path,
        save_path="./",
        pipeline=pipeline,
        img_sam=img_sam,
        visualize=False,
    )
    
    # Ensure mask_tensor is on the same device as masks
    mask_tensor = mask_tensor.to(device)
    
    # Process masks
    attn_map, mask_ids = [], []
    for mask_id, mask in enumerate(masks):
        if torch.sum(mask) > 0:
            attn_map.append(mask.unsqueeze(0))
            mask_ids.append(mask_id)
            
    matched_masks = [
        match_masks(
            mask_tensor,
            attn.to(mask_tensor.device),  # Ensure attn is on same device
            mask_list,
            iom_thres=config.car.iom_thres,
            min_pred_threshold=config.sam.min_pred_threshold,
        )
        for attn in attn_map
    ]
    
    for matched_mask, mask_id in zip(matched_masks, mask_ids):
        sam_masks = np.array([item["segmentation"] for item in matched_mask])
        sam_mask = np.any(sam_masks, axis=0)
        masks[mask_id] = torch.from_numpy(sam_mask).to(device)
        
    return masks
```

Then I ran into another error: `AttributeError: 'SAMPipeline' object has no attribute 'model'`. I am not sure if I did something wrong in previous fixing. It would be great if there is any solution could be shared. Thank you!

**Comment by kevin-ssy** [comment]
Hi,

I am not sure which repo that you are working on. Previously our code should be runnable on huggingface server and you can check those files at https://huggingface.co/spaces/kevinssy/CLIP_as_RNN/tree/main

Can you first try to run the code without SAM? There should be a way out using the existing code without any changes.

**Comment by suikei-wang** [comment]
Thanks for the reply! I resolved it a few days ago. I was using the repo under google research's github. Some minor bugs in huggingface's repo but easy to fix. Thank you!
