### ISSUE TITLE
Dataset preparation

### ISSUE THREAD

**Issue by ZhihuaLiuEd** [kevin-ssy/CLIP_as_RNN#4]
Hi there,

Thanks for your amazing work on CaR and congratulation on CVPR acceptance!
Will you provide the dataset preparation guidance from zero-shot segmentation to referring image segmentation and referring video segmentation?

Best,
Zhihua

**Comment by kevin-ssy** [comment]
Hi,

Thank you for your interests! You can refer to https://github.com/kevin-ssy/CLIP_as_RNN/blob/main/DATA.md for data preparation.
