### ISSUE TITLE
Demo.py

### ISSUE THREAD

**Issue by MrSecant** [kevin-ssy/CLIP_as_RNN#5]
Hi there,

Thanks for your great work and congratulations on CVPR acceptance!
Will you provide the script "demo.py" to support running it locally?

Best,
Yuhang

**Comment by runjiali-rl** [comment]
Hi thank you for your question
Please refer to this file and let me know if it runs
https://github.com/google-research/google-research/blob/master/clip_as_rnn/demo.py
